### ISSUE TITLE
Siden er nede... 

### ISSUE THREAD

**Issue by seel93** [seel93/meteor#2]
Errors prevented startup:

While building for web.browser:
client/modules/users/actions/users.js:21:56: Unexpected token (21:56)

While processing files with ecmascript (for target web.browser):
client/modules/users/actions/users.js:21:56: Unexpected token (21:56)
client/modules/users/containers/NewUser.js:24:25: Unexpected token (24:25)

Your application has errors. Waiting for file change.

fint om noen kunne tatt ut en branch og sett nærmere på problemmet, jobber med det selv men er redd for at det kan ta litt tid før jeg finner ut av det

**Comment by hungqt** [comment]
For denne er det en skrivefeil-error:
client/modules/users/actions/users.js:21:56: Unexpected token (21:56)

fom. kodelinje 17 og nedover i client/modules/users/actions/users.js står det LocalSate istedenfor LocalState

**Comment by hungqt** [comment]
Det står også LocalSate overalt i NewUser.js også

**Comment by seel93** [comment]
hehe, skal få fikset det
